### ISSUE TITLE
Perhaps incompatible with More New Fish mod?

### ISSUE THREAD

**Issue by vadie1** [captncraig/StardewMods#1]
I just added your mod and thought there should not be any problems, as you recently updated so it is compatible with Climates of Ferngill. However, while The Big One show showed up in the TV channel selection, nothing would happen and I repeatedly got this error: https://log.smapi.io/a0g4wfpy
Not sure why, but is it conflicting with the other mod I have More New Fish since it adds more fish and possibly the channel can't read it? Just wondering, as it causes the channel to be unusable.

**Comment by captncraig** [comment]
Interesting. My initial reaction was gonna be "I probably can't support that" if they did odd things besides just injecting resources. But that error looks like we may be close to working. I gotta dig into what they are doing though.

**Comment by captncraig** [comment]
I'm thinking it is a problem with that mod's data files. Some lines look a bit malformed from what I expect the data to look like:

```
"880": "Starfish/.35/682 .2/ocean/1/5",
"881": "Blue Starfish/.25/682 .35/ocean/1/3",
"882": "Royal Starfish/.25/682 .35/ocean/1/3",
```

I think should have `/trap/` as the second field. My code should be a bit more defensive I think, but unless I'm mistaken, that data is also bad.

**Comment by captncraig** [comment]
Found trent in discord, and he's updating that mod to fix. Good luck.
